name: autosure_app
description: "AutoSure Insurance App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_database: ^12.0.2
  firebase_auth: ^6.1.0
  firebase_storage: ^13.0.2
  google_fonts: ^6.3.2
  flutter_spinkit: ^5.2.2
  http: ^1.5.0
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/My_logo.jpg